version: "2.3"
services:
  search:
    image: julianbetz/yokome.search:1.0
    container_name: search
    environment:
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
    ulimits:
      nproc: 65536
      nofile: 65536
    expose:
      - 9200
      - 9300
    # ports:
    #   - 9200:9200
    #   - 9300:9300
    networks:
      - yokome_net
  app:
    image: julianbetz/yokome.app:1.0
    container_name: app
    environment:
      - ELASTICSEARCH_ADDRESS=inverse:9200
    links:
      - search:inverse
    depends_on:
      - search
    networks:
      - yokome_net
    expose:
      - 5003
    ports:
      - 5003:5003
networks:
  yokome_net:
